name: Publish to pypi
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Build pytdbot
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: |
          python -m pip install wheel
          python setup.py sdist bdist_wheel

      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
